//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double BatchSize {
            get {
                return ((double)(this["BatchSize"]));
            }
            set {
                this["BatchSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double HeaterEffect {
            get {
                return ((double)(this["HeaterEffect"]));
            }
            set {
                this["HeaterEffect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double TapTemp {
            get {
                return ((double)(this["TapTemp"]));
            }
            set {
                this["TapTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double STD_BatchSize {
            get {
                return ((double)(this["STD_BatchSize"]));
            }
            set {
                this["STD_BatchSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double STD_HeaterEffect {
            get {
                return ((double)(this["STD_HeaterEffect"]));
            }
            set {
                this["STD_HeaterEffect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double STD_TapTemp {
            get {
                return ((double)(this["STD_TapTemp"]));
            }
            set {
                this["STD_TapTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public double MashThickness {
            get {
                return ((double)(this["MashThickness"]));
            }
            set {
                this["MashThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.1")]
        public double GrainAbsorption {
            get {
                return ((double)(this["GrainAbsorption"]));
            }
            set {
                this["GrainAbsorption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.5")]
        public double STD_MashThickness {
            get {
                return ((double)(this["STD_MashThickness"]));
            }
            set {
                this["STD_MashThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.1")]
        public double STD_GrainAbsorption {
            get {
                return ((double)(this["STD_GrainAbsorption"]));
            }
            set {
                this["STD_GrainAbsorption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double PumpOnDuration {
            get {
                return ((double)(this["PumpOnDuration"]));
            }
            set {
                this["PumpOnDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double STD_PumpOnDuration {
            get {
                return ((double)(this["STD_PumpOnDuration"]));
            }
            set {
                this["STD_PumpOnDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double PumpOffDuration {
            get {
                return ((double)(this["PumpOffDuration"]));
            }
            set {
                this["PumpOffDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double STD_PumpOffDuration {
            get {
                return ((double)(this["STD_PumpOffDuration"]));
            }
            set {
                this["STD_PumpOffDuration"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Database\\Hops.bdb")]
        public string PathHopsDB {
            get {
                return ((string)(this["PathHopsDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Database\\Grains.bdb")]
        public string PathGrainsDB {
            get {
                return ((string)(this["PathGrainsDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Database\\Styles.bdb")]
        public string PathStylesDB {
            get {
                return ((string)(this["PathStylesDB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Database\\Recipes\\")]
        public string PathRecipesFolder {
            get {
                return ((string)(this["PathRecipesFolder"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double EquipmentLoss {
            get {
                return ((double)(this["EquipmentLoss"]));
            }
            set {
                this["EquipmentLoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double STD_EquipmentLoss {
            get {
                return ((double)(this["STD_EquipmentLoss"]));
            }
            set {
                this["STD_EquipmentLoss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.7")]
        public double STD_MashRatio {
            get {
                return ((double)(this["STD_MashRatio"]));
            }
            set {
                this["STD_MashRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2.7")]
        public double MashRatio {
            get {
                return ((double)(this["MashRatio"]));
            }
            set {
                this["MashRatio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Database\\Yeasts.bdb")]
        public string PathYeastsDB {
            get {
                return ((string)(this["PathYeastsDB"]));
            }
            set {
                this["PathYeastsDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bluetooth")]
        public string ConnectionType {
            get {
                return ((string)(this["ConnectionType"]));
            }
            set {
                this["ConnectionType"] = value;
            }
        }
    }
}
